name: mofe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.1
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  lottie: ^3.1.3
  provider: ^6.1.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/huskie/

flutter_native_splash:
  android: true
  color: "#2B2B2B"
  image: "assets/mofe.png"
  
  android_12:
    color: "#2B2B2B"
    image: "assets/mofe.png"