export const quotes: string[] = [
  "Dream big, work hard, stay focused, surround positivity.",
  "In the midst of chaos, there is also opportunity.",
  "Success is not final, failure is not fatal: It's the courage.",
  "Believe you can and you're halfway there.",
  "The only limit to our realization of tomorrow will be.",
  "Strive for progress, not perfection. Every step forward counts.",
  "Your time is limited, don't waste it living someone else's life.",
  "Change your thoughts and you change your world.",
  "The secret of getting ahead is getting started.",
  "The only way to do great work is to love what.",
  "It's not whether you get knocked down, it's whether you get.",
  "Do not wait to strike till the iron is hot.",
  "Believe in yourself and all that you are. Know that.",
  "Success is stumbling from failure to failure with no loss.",
  "Don't watch the clock; do what it does. Keep going.",
  "The best way to predict the future is to create.",
  "The future belongs to those who believe in the beauty.",
  "You are never too old to set another goal or.",
  "It always seems impossible until it is done.",
  "The only thing standing between you and your goal is.",
  "You don't have to be rich to travel well.",
  "Our greatest glory is not in never falling, but in.",
  "The only person you are destined to become is the.",
  "Be not afraid of life. Believe that life is worth.",
  "The only impossible journey is the one you never begin.",
];